FROM alpine:3.11
MAINTAINER sig-platform@spinnaker.io
RUN apk --no-cache add --update bash openjdk11-jre
RUN adduser -D -S spinnaker
COPY igor-web/build/install/igor /opt/igor
RUN mkdir -p /opt/igor/plugins && chown -R spinnaker:nogroup /opt/igor/plugins
USER spinnaker
CMD ["/opt/igor/bin/igor"]
